name: pihole
adopt-info: pihole
summary: Network-wide ad blocking via your own Linux hardware
description: |
  The Pi-hole® is a DNS sinkhole that protects your devices from unwanted content, without installing any client-side software.
    - Easy-to-install: our versatile installer walks you through the process, and takes less than ten minutes
    - Resolute: content is blocked in non-browser locations, such as ad-laden mobile apps and smart TVs
    - Responsive: seamlessly speeds up the feel of everyday browsing by caching DNS queries
    - Lightweight: runs smoothly with minimal hardware and software requirements
    - Robust: a command line interface that is quality assured for interoperability
    - Insightful: a beautiful responsive Web Interface dashboard to view and control your Pi-hole
    - Versatile: can optionally function as a DHCP server, ensuring all your devices are protected automatically
    - Scalable: capable of handling hundreds of millions of queries when installed on server-grade hardware
    - Modern: blocks ads over both IPv4 and IPv6
    - Free: open source software which helps ensure you are the sole person in control of your privacy

base: core20
grade: stable
confinement: strict

apps:
  pihole:
    command: pihole
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - network
      - network-bind
      - process-control
      - system-observe
      - hardware-observe
      - daemon-notify
      - log-observe
      - system-files
      
parts:
  pihole:
    plugin: nil
    source: https://github.com/pi-hole/pi-hole.git
    source-type: git
    
    override-build: |
     curl -sSL https://install.pi-hole.net | bash
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - curl

    stage-packages:
      - python3
      - php
      - php-sqlite3
      - whiptail 
      - dnsutils
      - dhcpcd5 
      - git
      - lighttpd
      - php-common
      - cron 
      - curl 
      - iputils-ping 
      - lsof 
      - netcat 
      - psmisc 
      - unzip 
      - wget 
      - idn2 
      - sqlite3 
      - libcap2-bin 
      - dns-root-data 
      - libcap2
      - libslang2
      - sudo
      - iproute2
      - libatm1
